### ISSUE TITLE
dbConnection sınıfında hata

### ISSUE THREAD

**Issue by muazkurt** [GTU-CSE343/Database#2]
Sınıf ismi ile dosya ismi uyuşmuyor,
Hatalar var compile olmuyor. 
@karginbilgehan 
[https://github.com/GTU-CSE343/Database/blob/master/BizTalkDB/src/dbConneciton.java](url)

**Comment by karginbilgehan** [comment]
Sınıf adı ile dosya ismi uyuşmadığından dolayı ilgili kısım silindi. Conneciton'ı sağlamak için gerekli olan kod hali hazırdı elimizde mevcut.

**Comment by karginbilgehan** [comment]
Sınıf adı ile dosya ismi uyuşmadığından dolayı ilgili kısım silindi. Conneciton'ı sağlamak için gerekli olan kod hali hazırda elimizde mevcut.
